version: '3.4'

services:
  database:
    image: postgres:10.17
    restart: always
    environment:
     - "POSTGRES_USER=postgres"
     - "POSTGRES_PASSWORD=HACKERNAOENTRA"
     - "POSTGRES_DB=Carrarapets_dbo"
    ports: 
     - 5432:5432
    volumes:
     - database-volume:\Program Files\PostgreSQL\14\data
  

volumes:
  database-volume:
  

