version: '3.4'

services:
  database:
    image: postgres:10.17
    restart: always
    environment:
     - "POSTGRES_USER=postgres"
     - "POSTGRES_PASSWORD=eptQcFAQzFE0JoF4Xq68"
     - "POSTGRES_DB=railway"
     - "POSTGRES_HOST=containers-us-west-78.railway.app"
     - "POSTGRES_PORT=5847"
    ports: 
     - 5847:5847
    volumes:
     - database-volume:\Program Files\PostgreSQL\14\data
  


volumes:
  database-volume:
  

